FROM mysql

ENV MYSQL_USER=jwheo
ENV MYSQL_PASSWORD=jwheo1234
ENV MYSQL_ROOT_PASSWORD=root1234
ENV MYSQL_DATABASE=jwheodb

CMD ["--character-set-server=utf8mb4", "--collation-server=utf8mb4_unicode_ci"]